travis:
  secure:
    BINSTAR_TOKEN: UtOgDN12pC3QpReLpnKPTLG9ZfDQ3WzwtEBYtQy1D6dlfcbNnkWqef5TIdWsuJfzJauxAmXDpX2dkK6GkBtBs89qr/C+QZHqSLL4Ul83cBaEKrcjNlxwV4M2xUgJezoSQS6dmNDPig1Y7DFozC6LRwwganmTnFFQUOrbsfDMPK/Mp9TiBDhOq+B9oy7GQ7kqsnHSQ1Z4PEFqNWdeIAudipipW3P0bGEoyxRpbVoEpXOKzuLKrQkdFRps592TPBQBwt94srO/+NZEbjDPGTkwxOQfjiDeHSPFclOV7T5euS+fBUYEZfRojk7NzlbBD/MBbuljGH6VUDcXTaXWWVDdoSerIp+WXiX1sLPbYG3gFWyOfO5KU9fMT4w1iwhbZCJ9FwfzL/sdxB2b4RiWAPAsm5b2KX3TeniF4Ktqf+Lb7HHM9C7Pxps8N2cojZDDkPiSUJ7/IYhllAUh3Yq/FmyQkZCTvEaPk6ppALA5svHaxyRh+PLNG+4bQPbWbbQyNVK0AFTC+oSZmogHX8c7zySAOKZGaGs9f0lsh1/apDXYtwcRRzf/3iCknRiE6v9U0XglKG1bPHq+khn4EsOCnxSr0J7wTQpLdctuC7vD2hrBYaNP0SiyJD80BmAKcykrdwNfHyarzkGNUsDBpsdO5mWEbp4udmVOWgvBV0s2RVW37UI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
